FROM python:3.9-slim

RUN apt-get update && apt-get install g++ -y

WORKDIR /app

COPY requirements.txt .
COPY requirements-drift-monitor.txt . 

RUN pip install --no-cache-dir --upgrade -r requirements.txt \
  && pip install --no-cache-dir --upgrade -r requirements-drift-monitor.txt

COPY lib lib
COPY drift_monitor drift_monitor
COPY output output

EXPOSE 8080

CMD ["uvicorn", "drift_monitor.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]