FROM python:3.9-slim

WORKDIR /app

COPY requirements-scraper.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY scrapy.cfg .
COPY scraper scraper

EXPOSE 9000

# Run the crawler when the container launches.
CMD [ "scrapy", "crawl", "questions" ]