FROM python:3.9-slim

WORKDIR /app

COPY requirements-so-so-agent.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY src src
COPY so_agent so_agent

EXPOSE 8080

CMD ["uvicorn", "so_agent.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]