# TODO
# - add google drive for storage and model
#   - 1g_sGxwElkh3qHKSR86hExgqI4TvfILb4 <- this is the url code for the google drive folder, should be added by the following commands
#   running in the command line: 
#     - dvc add data(set)
#     - dvc remote add --default myremote 1g_sGxwElkh3qHKSR86hExgqI4TvfILb4
#     - dvc push
#     enter the verification code (Julian)
# - output for the model should be changed so it supports multiple models

stages:
  load_data:
    cmd: poetry run python -m code.load_data.py
    deps:
    - data
    - code/load_data.py
  preprocess:
    cmd: poetry run python -m code.preprocess_data.py
    deps:
    - data
    - code/preprocess_data.py
    outs:
    - data/train.joblib
    - data/val.joblib
    - data/test.joblib
  train:
    cmd: poetry run python -m code.train_classifier.py
    deps:
    - output
    - code/text_classification.py
    outs:
    - output/model.joblib
  eval:
    cmd: poetry run python -m code.eval.py
    deps:
    - output
    - code/eval.py
    # We want probably generate some sort of report here?
    # metrics:
    #   - summary.json:
    #       cache: false
  serve:
    cmd: poetry run python -m code.serve_model.py
    deps:
    - output