stages:
  preprocess:
    cmd: python -m pipeline.preprocess
    deps:
      - data/raw/raw.tsv
      - src
      - pipeline/preprocess.py
    outs:
      - data/processed/preprocessed.csv
  gen_schema:
    cmd: python -m pipeline.gen_schema
    deps:
      - data/processed/preprocessed.csv
      - src
      - pipeline/gen_schema.py
    outs:
      - output/data/schema.txt
  validate:
    cmd: python -m pipeline.validate
    deps:
      - output/data/schema.txt
      - data/processed/preprocessed.csv
      - src
      - pipeline/validate.py
    outs:
      - data/processed/train.joblib
      - data/processed/validation.joblib
  train:
    cmd: python -m pipeline.train
    deps:
      - data/processed/train.joblib
      - data/processed/validation.joblib
      - src
      - pipeline/train.py
    outs:
      - output/models/BagOfWords.joblib
      - output/models/TFIDF.joblib
    metrics:
      - output/BagOfWords.json:
          cache: false
      - output/TFIDF.json:
          cache: false
  test:
    cmd: pytest --junitxml=reports/tests.xml --cov=src --cov-report=xml:reports/coverage.xml
    deps:
      - output/models/BagOfWords.joblib
      - output/models/TFIDF.joblib
      - src
      - tests
    outs:
      - reports/tests.xml:
          cache: false
      - reports/coverage.xml:
          cache: false