apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  labels:
    app: model-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
      - name: model-api
        image: ghcr.io/julianbiesheuvel/remla_so-service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-pat
---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: model-svc
spec:
  type: NodePort
  selector:
    app: model-api
  ports:
    - port: 8080
      targetPort: 8080
      # open for debug
      nodePort: 30042
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    # release matches helm install name for the kube-prometheus-stack
    release: promstack
spec:
  selector:
    matchLabels:
      app: model-svc
  endpoints:
  - targetPort: 8080
    path: "/metrics"
    interval: 1s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service:
      name: service
      port:
        number: 8080

# kubectl create secret docker-registry ghcr-pat --docker-server=ghcr.io --docker-username=jfkakajfk --docker-password=***

# connect to pod
# kubectl port-forward <name> -p from:to

# connect to service
# kubectl port-forward svc/<service> from:to