# This file contains overrides for the bitnami pg helm chart
# see https://artifacthub.io/packages/helm/bitnami/postgresql

global:
  postgresql:
    auth:
      username: "remla"
      database: "remla"
      existingSecret: pg-secrets # use the secrets from k8s.yml
    service:
      ports:
        postgresql: 5432
primary:
  initdb:
    scripts:
      schema.sql: | # this feels weird^^
        create table questions
        (
            id         int                     not null primary key,
            title      text                    not null,
            tags       text                    not null,
            created_at timestamp default now() not null
        );
  persistence:
    enabled: true
    size: 8Gi
metrics:
  enabled: true
  ## Define additional custom metrics
  ## https://github.com/wrouesnel/postgres_exporter#adding-new-metrics-via-a-config-file
  ## customMetrics:
  ##   pg_database:
  ##     query: "SELECT d.datname AS name, CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE 0 END AS size_bytes FROM pg_catalog.pg_database d where datname not in ('template0', 'template1', 'postgres')"
  ##     metrics:
  ##       - name:
  ##           usage: "LABEL"
  ##           description: "Name of the database"
  ##       - size_bytes:
  ##           usage: "GAUGE"
  ##           description: "Size of the database in bytes"
  ##
  customMetrics: {}
  containerPorts:
    metrics: 9187
  serviceMonitor:
    enabled: true
    interval: 1m
    labels:
      release: promstack
  