name: Runs the DVC Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      # - uses: iterative/setup-dvc@v1
      #   with:
      #     version: '2.10.2'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache
      - uses: snok/install-poetry@v1
        with:
          version: '1.2.0b2'
      - run: | # scikit-multiflow needs this to be 2 installs
          poetry install --sync --with dev,pipeline,model-api,main --without=drift-monitor,scraper,so-agent

      - name: DVC
        run: |
          poetry run dvc remote modify myremote gdrive_use_service_account true
          poetry run dvc pull
          poetry run dvc repro
          poetry run dvc push
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}